NB_CLASSES = 128
NB_WORKERS = 1
IMAGE_SIZE = 224
MODEL_FILE = ''

# Attack control
ADV_LR = 1
ITERATIONS = 10
DECAY_ITER = 600
ATTACK_BATCH = 1
ATTACK_CLAMP = 0.1
ATTACK_DECAY = 0.01
ATTACK_SPLIT = True
ATTACK_IDX_S = 0
ATTACK_IDX_E = 40000
ATTACK_SAVE_PATH = 'data_tc'
